;编写一段显示字符串STRING的程序
DATA SEGMENT
    STRING DB 'MY NAME IS LAMBFISHNAB !',0DH,0AH,'$'
    COUNT DB $-STRING
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX
    LEA BX,STRING
    MOV CX,WORD PTR COUNT
NEXT:
    MOV DL,[BX]
    MOV AH,02H
    INT 21H
    INC BX
    LOOP NEXT
    MOV AH,4CH
    INT 21H
CODE ENDS
END START