DATA SEGMENT
    STRING DB 'I AM YYZ !',0DH,0AH,'$'
    COUNT DB $-STRING
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX
    MOV CX,WORD PTR COUNT
    XOR SI,SI
NEXT:
    MOV DL,STRING[SI]
    MOV AH,02H
    INT 21H
    INC SI
    LOOP NEXT
    MOV AH,4CH
    INT 21H
CODE ENDS
END START