DATA SEGMENT
    STRING DB 'HELLO EVERYONE , I AM YYZ',0AH,0DH
    COUNT DB $-STRING
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX
    LEA BX,STRING
    MOV CX,WORD PTR COUNT
L1:
    MOV DL,[BX]
    INC BX
    MOV AH,02H
    INT 21H
    LOOP L1
    MOV AH,4CH
    INT 21H
CODE ENDS
END START